/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ErMcB6406
 */
public class RPG4_ATTACK extends javax.swing.JFrame {

    /**
     * Creates new form RPG4_ATTACK
     */
    public RPG4_ATTACK() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        RPG4_ATTACK = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        continueButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        GameText2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpgwolf_morecolour_fringe.png"))); // NOI18N
        jLabel5.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RPG4_ATTACK.setBackground(new java.awt.Color(0, 0, 0));

        Title.setFont(new java.awt.Font("Wet Pet", 0, 48)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("In the mists of aeriden");
        Title.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Title.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        continueButton.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        continueButton.setText("CONTINUE");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpgwolf_morecolour_fringe.png"))); // NOI18N
        jLabel4.setText("jLabel2");

        GameText2.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        GameText2.setForeground(new java.awt.Color(255, 255, 255));
        GameText2.setText("<html> * You decided to attack the guard <br> * You draw your rusty sword and <br> &nbsp;\nswing at the sentry <br> * You have either overestimated your skill <br> &nbsp; or the guard has god level power <br> * You lose 1 HP");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpgwolf_morecolour_fringe.png"))); // NOI18N
        jLabel6.setText("jLabel2");

        javax.swing.GroupLayout RPG4_ATTACKLayout = new javax.swing.GroupLayout(RPG4_ATTACK);
        RPG4_ATTACK.setLayout(RPG4_ATTACKLayout);
        RPG4_ATTACKLayout.setHorizontalGroup(
            RPG4_ATTACKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RPG4_ATTACKLayout.createSequentialGroup()
                .addGroup(RPG4_ATTACKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RPG4_ATTACKLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Title))
                    .addGroup(RPG4_ATTACKLayout.createSequentialGroup()
                        .addGroup(RPG4_ATTACKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RPG4_ATTACKLayout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(GameText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RPG4_ATTACKLayout.createSequentialGroup()
                                .addGap(246, 246, 246)
                                .addComponent(continueButton)))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(50, 50, 50))
            .addGroup(RPG4_ATTACKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RPG4_ATTACKLayout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(516, 516, 516)))
        );
        RPG4_ATTACKLayout.setVerticalGroup(
            RPG4_ATTACKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RPG4_ATTACKLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Title)
                .addGap(29, 29, 29)
                .addGroup(RPG4_ATTACKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GameText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(42, 42, 42)
                .addComponent(continueButton)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(RPG4_ATTACKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RPG4_ATTACKLayout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addComponent(jLabel4)
                    .addContainerGap(144, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RPG4_ATTACK, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RPG4_ATTACK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed

        this.setVisible(false);
        new RPG3().setVisible(true);
        
        RPG3.playerHP = RPG3.playerHP - 1;
    }//GEN-LAST:event_continueButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPG4_ATTACK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPG4_ATTACK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RPG4_ATTACK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPG4_ATTACK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RPG4_ATTACK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GameText2;
    private javax.swing.JPanel RPG4_ATTACK;
    private javax.swing.JLabel Title;
    private javax.swing.JButton continueButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
