/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ErMcB6406
 */
public class RPG5_NORTH_RIGHT extends javax.swing.JFrame {

    /**
     * Creates new form RPG5_NORTH_RIGHT
     */
    public RPG5_NORTH_RIGHT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        RPG5_NORTH_RIGHT = new javax.swing.JPanel();
        Title1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        GameText4 = new javax.swing.JLabel();
        RETURN1 = new javax.swing.JButton();
        TOUCH = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wolfsmaller.png"))); // NOI18N
        jLabel7.setText("jLabel2");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wolfsmaller.png"))); // NOI18N
        jLabel6.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RPG5_NORTH_RIGHT.setBackground(new java.awt.Color(0, 0, 0));

        Title1.setFont(new java.awt.Font("Wet Pet", 0, 48)); // NOI18N
        Title1.setForeground(new java.awt.Color(255, 255, 255));
        Title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title1.setText("In the mists of aeriden");
        Title1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Title1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Title1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shroom.png"))); // NOI18N
        jLabel5.setText("jLabel2");

        GameText4.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        GameText4.setForeground(new java.awt.Color(255, 255, 255));
        GameText4.setText("<html> * You choose to go down the right path <br> * You continue walking until the path <br> &nbsp; suddenly stops <br>\n* You look around your whereabouts <br> * To your amazment, the trail has led you <br> &nbsp; deep into the forest where the light barley <br> &nbsp; breaks through the upper canopy <br> * Glowing mushrooms are littered throughout <br> &nbsp; the forest\nas far as the eye can see <br> * You want to touch one, but you don't <br> &nbsp; know if they are harmful <br> * What would you like to do?");

        RETURN1.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        RETURN1.setText("RETURN");
        RETURN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RETURN1ActionPerformed(evt);
            }
        });

        TOUCH.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        TOUCH.setText("TOUCH");
        TOUCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOUCHActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wolfsmaller.png"))); // NOI18N
        jLabel15.setText("jLabel2");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wolfsmaller.png"))); // NOI18N
        jLabel16.setText("jLabel2");

        javax.swing.GroupLayout RPG5_NORTH_RIGHTLayout = new javax.swing.GroupLayout(RPG5_NORTH_RIGHT);
        RPG5_NORTH_RIGHT.setLayout(RPG5_NORTH_RIGHTLayout);
        RPG5_NORTH_RIGHTLayout.setHorizontalGroup(
            RPG5_NORTH_RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RPG5_NORTH_RIGHTLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(RPG5_NORTH_RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Title1)
                    .addGroup(RPG5_NORTH_RIGHTLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(RPG5_NORTH_RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RPG5_NORTH_RIGHTLayout.createSequentialGroup()
                                .addComponent(TOUCH)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(RETURN1))
                            .addGroup(RPG5_NORTH_RIGHTLayout.createSequentialGroup()
                                .addComponent(GameText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        RPG5_NORTH_RIGHTLayout.setVerticalGroup(
            RPG5_NORTH_RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RPG5_NORTH_RIGHTLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Title1)
                .addGroup(RPG5_NORTH_RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RPG5_NORTH_RIGHTLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(RPG5_NORTH_RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)))
                    .addGroup(RPG5_NORTH_RIGHTLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(GameText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addGroup(RPG5_NORTH_RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RETURN1)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TOUCH))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RPG5_NORTH_RIGHT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RPG5_NORTH_RIGHT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RETURN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RETURN1ActionPerformed
        this.setVisible(false);
        new RPG5_NORTH().setVisible(true);
    }//GEN-LAST:event_RETURN1ActionPerformed

    private void TOUCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOUCHActionPerformed
        this.setVisible(false);
        new RPG5_NORTH_RIGHT_MUSHROOM().setVisible(true);
    }//GEN-LAST:event_TOUCHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPG5_NORTH_RIGHT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPG5_NORTH_RIGHT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RPG5_NORTH_RIGHT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPG5_NORTH_RIGHT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RPG5_NORTH_RIGHT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GameText4;
    private javax.swing.JButton RETURN1;
    private javax.swing.JPanel RPG5_NORTH_RIGHT;
    private javax.swing.JButton TOUCH;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
