
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ErMcB6406
 */
public class RPG5_WEST extends javax.swing.JFrame {

    /**
     * Creates new form RPG5_WEST
     */
    public RPG5_WEST() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        RPG5_WEST = new javax.swing.JPanel();
        Title12 = new javax.swing.JLabel();
        GameText14 = new javax.swing.JLabel();
        ATTACK = new javax.swing.JButton();
        RETURN = new javax.swing.JButton();
        Image3 = new javax.swing.JLabel();
        Image4 = new javax.swing.JLabel();

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wolfsmaller.png"))); // NOI18N
        jLabel28.setText("jLabel2");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wolfsmaller.png"))); // NOI18N
        jLabel27.setText("jLabel2");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wolfsmaller.png"))); // NOI18N
        jLabel16.setText("jLabel2");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wolfsmaller.png"))); // NOI18N
        jLabel17.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RPG5_WEST.setBackground(new java.awt.Color(0, 0, 0));

        Title12.setFont(new java.awt.Font("Wet Pet", 0, 48)); // NOI18N
        Title12.setForeground(new java.awt.Color(255, 255, 255));
        Title12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title12.setText("In the mists of aeriden");
        Title12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Title12.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Title12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        GameText14.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        GameText14.setForeground(new java.awt.Color(255, 255, 255));
        GameText14.setText("<html> * You choose to walk west <br> * On the trail, you notice that more and more mist begin to seep from the ground <br> * You feel unnerved, like someone is watching you, but you can barely see <br> * What was that, moving in the security of the shadows? <br> * You feel your sins crawling up your back, <br> &nbsp; but the thrill of this cat and mouse game is too exhilarating <br> * You smile to yourself and look straight ahead <br> * You thrive in the knowledge that an imminent <br> &nbsp; fight will take place soon <br> * You continue down the now dark and dreary path that leads you closer <br> &nbps; to bloodshed <br> * You are forced to stop when a large thicket of thorns block the trail <br> * You remember about that new shiny longsword you found, <br> &nbsp; and an idea sparks in your head  <br> * Your short time goal is to attack the thicket <br> * What do you want to do?");

        ATTACK.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        ATTACK.setText("ATTACK");
        ATTACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATTACKActionPerformed(evt);
            }
        });

        RETURN.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        RETURN.setText("RETURN");
        RETURN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RETURNActionPerformed(evt);
            }
        });

        Image3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestbigwolf.png"))); // NOI18N
        Image3.setText("jLabel1");

        Image4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestbigwolf.png"))); // NOI18N
        Image4.setText("jLabel1");

        javax.swing.GroupLayout RPG5_WESTLayout = new javax.swing.GroupLayout(RPG5_WEST);
        RPG5_WEST.setLayout(RPG5_WESTLayout);
        RPG5_WESTLayout.setHorizontalGroup(
            RPG5_WESTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RPG5_WESTLayout.createSequentialGroup()
                .addGroup(RPG5_WESTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RPG5_WESTLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Image4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(RPG5_WESTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RPG5_WESTLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(Title12)
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RPG5_WESTLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GameText14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(Image3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RPG5_WESTLayout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(ATTACK)
                        .addGap(55, 55, 55)
                        .addComponent(RETURN)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        RPG5_WESTLayout.setVerticalGroup(
            RPG5_WESTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RPG5_WESTLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(RPG5_WESTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title12)
                    .addGroup(RPG5_WESTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Image3)
                        .addComponent(Image4)
                        .addComponent(GameText14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(RPG5_WESTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ATTACK)
                    .addComponent(RETURN))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RPG5_WEST, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RPG5_WEST, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ATTACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATTACKActionPerformed
        this.setVisible(false);
        new RPG5_ATTACK_PUZZLE().setVisible(true);
    }//GEN-LAST:event_ATTACKActionPerformed

    private void RETURNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RETURNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RETURNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPG5_WEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPG5_WEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            java.util.logging.Logger.getLogger(RPG5_WEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPG5_WEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(RPG5_WEST.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RPG5_WEST().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ATTACK;
    private javax.swing.JLabel GameText14;
    private javax.swing.JLabel Image3;
    private javax.swing.JLabel Image4;
    private javax.swing.JButton RETURN;
    private javax.swing.JPanel RPG5_WEST;
    private javax.swing.JLabel Title12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    // End of variables declaration//GEN-END:variables
}
